#!/bin/bash
# =============================================================================
# mucf_scan.sh - parameter scan for muon injection into a liquid D-T cell.
#
# For every (deuterium fraction, beam energy) point this script generates a
# D-T cell GDML (geometry as gdml/dt_target_mucf.gdml, with the material and
# window thickness substituted), generates a macro, runs g4sim, and collects
# the output. If ROOT is available it also appends one summary row per point
# (fraction of muons Bragg-peak-stopped inside the D-T, mean stopping depth)
# to scan_results/summary.csv.
#
# Run inside the g4targetpractice Docker image (script is shipped at
# /app/scans/mucf_scan.sh, executable at /app/build/g4sim):
#
#   docker run --rm -v "$PWD":/work -w /work \
#     -e ENERGIES="14 18 22 26 30 34" -e DFRACS="0.3 0.5 0.7" \
#     --entrypoint bash ghcr.io/lawrenceleejr/g4targetpractice:main \
#     /app/scans/mucf_scan.sh
#
# Or locally: G4SIM=./build/g4sim scans/mucf_scan.sh
#
# Parameters (environment variables):
#   ENERGIES    muon kinetic energies in MeV    (default "14 16 ... 34")
#   DFRACS      atomic deuterium fractions, 0<f<1 ok; 0/1 allowed (default "0.5")
#   PHI         density relative to liquid-hydrogen atom density
#               4.25e22 atoms/cm3               (default 1.0)
#   WINDOW_MM   steel window/wall thickness, mm (default 2)
#   NEVENTS     events per scan point           (default 2000)
#   PARTICLE    beam particle                   (default mu-)
#   G4SIM       path to g4sim executable        (default /app/build/g4sim)
#
# Results: scan_results/mucf_fD<frac>_E<energy>MeV.root (+ .log, generated
# .gdml/.mac in scan_results/config/, summary.csv).
# =============================================================================
set -euo pipefail

ENERGIES=${ENERGIES:-"14 16 18 20 22 24 26 28 30 32 34"}
DFRACS=${DFRACS:-"0.5"}
PHI=${PHI:-1.0}
WINDOW_MM=${WINDOW_MM:-2}
NEVENTS=${NEVENTS:-2000}
PARTICLE=${PARTICLE:-mu-}
G4SIM=${G4SIM:-/app/build/g4sim}

OUTDIR=scan_results
CFGDIR=$OUTDIR/config
mkdir -p "$CFGDIR"

# ROOT summary macro (file name must match function name)
SUMMARY_C=$CFGDIR/mucf_summary.C
cat > "$SUMMARY_C" << 'EOF'
void mucf_summary(const char* fn)
{
    TFile f(fn);
    TTree* t = (TTree*)f.Get("tree");
    if (!t || t->GetEntries() == 0) { printf("SCANROW,nan,nan,nan\n"); return; }
    double tot = t->GetEntries();
    // stopped (primaryEndE ~ 0) inside the D-T volume: 0 < z < 200 mm, |x|,|y| < 50 mm
    TString sel = "primaryEndE<0.1 && primaryEndZ>0 && primaryEndZ<200 && abs(primaryEndX)<50 && abs(primaryEndY)<50";
    double stop = t->GetEntries(sel);
    t->Draw("primaryEndZ>>hh(200,0,200)", sel, "goff");
    TH1* h = (TH1*)gDirectory->Get("hh");
    printf("SCANROW,%g,%g,%g\n", tot, stop / tot, (h && stop > 0) ? h->GetMean() : -1.0);
}
EOF

SUMMARY_CSV=$OUTDIR/summary.csv
[ -f "$SUMMARY_CSV" ] || echo "d_fraction,energy_MeV,events,stopped_in_DT_fraction,mean_stop_depth_mm" > "$SUMMARY_CSV"

for FD in $DFRACS; do
    # Mass fractions and density at atom density PHI * 4.25e22 cm^-3
    read -r RHO WD WT <<< "$(awk -v fd="$FD" -v phi="$PHI" 'BEGIN{
        md=2.0141; mt=3.0160;
        mbar = fd*md + (1-fd)*mt;
        printf "%.6g %.6g %.6g", phi*4.25e22*mbar/6.022e23, fd*md/mbar, (1-fd)*mt/mbar }')"
    # Vessel outer dimensions for the requested wall thickness
    read -r OXY OZ <<< "$(awk -v t="$WINDOW_MM" 'BEGIN{ printf "%.6g %.6g", 10+2*t/10, 20+2*t/10 }')"

    # Skip zero-weight fractions (Geant4 rejects them) for pure D or pure T
    MATFRACS=""
    [ "$(awk -v w="$WD" 'BEGIN{print (w>0)?1:0}')" = 1 ] && MATFRACS="$MATFRACS      <fraction n=\"$WD\" ref=\"Deuterium\"/>\n"
    [ "$(awk -v w="$WT" 'BEGIN{print (w>0)?1:0}')" = 1 ] && MATFRACS="$MATFRACS      <fraction n=\"$WT\" ref=\"Tritium\"/>\n"

    GDML=$CFGDIR/dt_cell_fD${FD}.gdml
    cat > "$GDML" << EOF
<?xml version="1.0"?>
<!-- Generated by mucf_scan.sh: fD=$FD, phi=$PHI, window=${WINDOW_MM} mm -->
<gdml>
  <materials>
    <isotope name="Deuteron" Z="1" N="2"><atom unit="g/mole" value="2.0141"/></isotope>
    <isotope name="Triton"   Z="1" N="3"><atom unit="g/mole" value="3.0160"/></isotope>
    <element name="Deuterium"><fraction n="1.0" ref="Deuteron"/></element>
    <element name="Tritium"><fraction n="1.0" ref="Triton"/></element>
    <material name="LiquidDT" state="liquid">
      <T unit="K" value="20"/>
      <D unit="g/cm3" value="$RHO"/>
$(printf "%b" "$MATFRACS")    </material>
  </materials>

  <solids>
    <box name="WorldBox"  x="60"   y="60"   z="100" lunit="cm"/>
    <box name="VesselBox" x="$OXY" y="$OXY" z="$OZ" lunit="cm"/>
    <box name="DTBox"     x="10"   y="10"   z="20"  lunit="cm"/>
  </solids>

  <structure>
    <volume name="DT_vol">
      <materialref ref="LiquidDT"/>
      <solidref ref="DTBox"/>
    </volume>
    <volume name="Vessel_vol">
      <materialref ref="G4_STAINLESS-STEEL"/>
      <solidref ref="VesselBox"/>
      <physvol><volumeref ref="DT_vol"/><position x="0" y="0" z="0"/></physvol>
    </volume>
    <volume name="World">
      <materialref ref="G4_Galactic"/>
      <solidref ref="WorldBox"/>
      <physvol><volumeref ref="Vessel_vol"/><position x="0" y="0" z="10" unit="cm"/></physvol>
    </volume>
  </structure>

  <setup name="Default" version="1.0">
    <world ref="World"/>
  </setup>
</gdml>
EOF

    for E in $ENERGIES; do
        TAG=fD${FD}_E${E}MeV
        MAC=$CFGDIR/scan_$TAG.mac
        cat > "$MAC" << EOF
/detector/readGDML $GDML
/run/initialize
/gun/particle    $PARTICLE
/gun/energyMode  mono
/gun/energy      $E MeV
/gun/position    0 0 -20 cm
/gun/direction   0 0 1
/run/printProgress 1000
/run/beamOn $NEVENTS
EOF

        echo ">>> fD=$FD  E=$E MeV  (rho=$RHO g/cm3, window=$WINDOW_MM mm, $NEVENTS events)"
        "$G4SIM" "$MAC" > "$OUTDIR/mucf_$TAG.log" 2>&1
        mv output.root "$OUTDIR/mucf_$TAG.root"

        if command -v root > /dev/null 2>&1; then
            ROW=$(root -l -b -q "$SUMMARY_C(\"$OUTDIR/mucf_$TAG.root\")" 2> /dev/null | grep '^SCANROW' | head -1)
            echo "$FD,$E,${ROW#SCANROW,}" >> "$SUMMARY_CSV"
            echo "    stopped-in-DT fraction, mean depth: ${ROW#SCANROW,}"
        fi
    done
done

echo ""
echo "Scan complete. Results in $OUTDIR/:"
[ ! -f "$SUMMARY_CSV" ] || column -t -s, "$SUMMARY_CSV" 2> /dev/null || cat "$SUMMARY_CSV"
